### ISSUE TITLE
Generalization of robot force-relevant skills through adapting compliant profiles

### ISSUE THREAD

**Issue by liujun0808** [PsorTheDoctor/adaptive-admittance-ctrl#1]
请问这些源码是对应标题中的那篇文章吗？

**Comment by PsorTheDoctor** [comment]
Yes, but it's unofficial.
________________________________
Od: liujun0808 ***@***.***>
Wysłane: poniedziałek, 17 czerwca 2024 10:07
Do: PsorTheDoctor/adaptive-admittance-ctrl ***@***.***>
DW: Subscribed ***@***.***>
Temat: [PsorTheDoctor/adaptive-admittance-ctrl] Generalization of robot force-relevant skills through adapting compliant profiles (Issue #1)


请问这些源码是对应标题中的那篇文章吗？
